### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by simkim** [simkim/dlcenter#20]
Background is random, UI is not clear on white background :+1: 
![Capture d’écran du 2020-05-02 14-28-10](https://user-images.githubusercontent.com/1174971/80864361-623ca480-8c82-11ea-80e7-20b83db2407f.png)

**Comment by genezys** [comment]
At first, I was using a `backdrop-filter` to unsaturate & blur the background. But that messes up the rendering engine of Chrome, I don't know why.

**Comment by genezys** [comment]
I also tried a `box-shadow` to add contrast to the UI but same, it triggered a rendering engine error in Safari...

**Comment by genezys** [comment]
Since `backdrop-filter` is gone, I can use `box-shadow` again. It helps separate the UI from the image. I also reduced the transparency and added a border to the shares.

<img width="1439" alt="Capture d’écran 2020-05-02 à 15 28 55" src="https://user-images.githubusercontent.com/65271/80865433-c6169b80-8c89-11ea-9b3f-9a812401180d.png">

**Comment by simkim** [comment]
cool
